### ISSUE TITLE
Remove hard-coded "dub build" and add support fur "dub test".

### ISSUE THREAD

**Issue by chris0210** [bruno-medeiros/DDT#60] opened 2014-05-04 09:49 UTC
Only a minor change request: currently each build is initiated by "dub build".  In order to test libraries, which have no main()-function, dub offers the "dub test" command, which generates a main()-function and then does the same as "dub build". It would be nice of one could choose in the build-properties panel whether to call the "build" or the "test" command.

**Comment by bruno-medeiros** [comment] 2015-08-04 18:49
Duplicate of #49

**Closed by bruno-medeiros** 2015-08-04 18:49 UTC
